echo ....Pulling Initial Data From The Repo....
git pull
echo Acha ab Changes Nhi Honge Ig
git add .
git reset base.sh
echo Enter message to add to commit:
read msg
echo ....Committing all staged files to remote repo....
git commit -m "$msg"
echo ....Pushing commit to remote repo....
git push
echo ....Ho Gya Kam Kya....
